---
permalink: config/concept-configuring-the-destination-and-schedule-for-database-dump-backups.html 
sidebar: sidebar 
keywords:  
summary: 您可以配置 Unified Manager 数据库转储备份设置，以设置数据库备份路径，保留数量和备份计划。您可以启用每日或每周计划备份。默认情况下，计划的备份处于禁用状态，但您应设置备份计划。 
---
= 配置数据库转储备份的目标和计划
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以配置 Unified Manager 数据库转储备份设置，以设置数据库备份路径，保留数量和备份计划。您可以启用每日或每周计划备份。默认情况下，计划的备份处于禁用状态，但您应设置备份计划。



== 开始之前

* 您必须具有操作员，应用程序管理员或存储管理员角色。
* 在定义为备份路径的位置中，必须至少有 150 GB 的可用空间。
+
建议使用 Unified Manager 主机系统外部的远程位置。

* 如果Unified Manager安装在Linux系统上、请验证"`jboss`"用户是否具有对备份目录的写入权限。
* 在Unified Manager收集15天的历史性能数据时、您不应计划在添加新集群后立即执行备份操作。




== 关于此任务

与后续备份相比，首次执行备份所需的时间要多，因为第一次备份是完整备份。完整备份可能超过 1 GB ，并且可能需要三到四个小时。后续备份是增量备份，所需时间更短。

[NOTE]
====
如果您发现增量备份文件的数量过大，无法容纳为备份分配的空间，则可以定期创建新的完整备份，以替换旧的完整备份及其所有子增量文件。另外，如果 Unified Manager 安装在 Linux 系统上，则您可能需要开始使用 NetApp Snapshot 备份方法。

====


== 步骤

. 在左侧导航窗格中，单击 * 常规 * > * 数据库备份 * 。
. 在 * 数据库备份 * 页面中，单击 * 备份设置 * 。
. 为备份路径，保留数量和计划配置适当的值。
+
保留数量的默认值为 10 ；您可以使用 0 创建无限备份。

. 选择 * 计划每日 * 或 * 计划每周 * 按钮，然后指定计划详细信息。
. 单击 * 应用 * 。




== 结果

数据库转储备份文件会根据计划创建。您可以在数据库备份页面中查看可用的备份文件。

* 相关信息 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_start_a_new_Incremental_Backup_chain_within_ActiveIQ_Unified_Manager_versions_7.2_through_9.6["如何在Active IQ Unified Manager 中启动新的增量备份链"^]
